# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-feed, jekyll-seo-tag] #[jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
#excerpt_separator:   "<!--excerpt-end-->"

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "La Page Folle"
description:	       "Un blog sur le cinéma fantastique"
author:              "Pantalons Inappropriés"
locale:              fr_FR

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

defaults:
  -
    scope:
      path:            "assets/**/*"
    values:
      sitemap:         false
