# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'la-page-folle'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-849DW5G21W'

menu:
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Critiques',          url: 'critiques'}
- {name: 'Par décennie',       url: 'decennies'}
- {name: 'Par pays',           url: 'pays'}
- {name: 'Par genre',          url: 'genres'}
- {name: 'Catégories',         url: 'tags'}
#- {name: 'Documentation',      url: 'documentation'}
- {name: 'A propos',           url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter',    link: 'https://twitter.com/paululele'}
#- {icon: 'facebook',   link: 'https://www.facebook.com/paululele'}
#- {icon: 'instagram',  link: 'https://instagram.com/paululele'}
- {icon: 'envelope',   link: 'mailto:pantalon.inapproprie@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Plus récent'
  previous_page: 'Plus ancien'

sharing_button_prompt: 'Partager :'

related_posts: 'Vous aimerez aussi...'

post_date_prefix: 'Ecrit le'
